services:
  homeassistant:
    container_name: ha-dev
    image: ghcr.io/home-assistant/home-assistant:stable@sha256:3e6710a7ab2a61311d9d899b719f6c3657791c63e8f4942cec4ebc42401d6b76
    restart: unless-stopped
    ports:
      - "8124:8123"
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
