services:
  homeassistant:
    container_name: ha-dev
    image: ghcr.io/home-assistant/home-assistant:stable@sha256:130241f28d01fa80dfa3b44f7d89781c188d8642ecab9024f079f19f9f82baa0
    restart: unless-stopped
    ports:
      - "8124:8123"
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
